# Generated by Django 3.1.1 on 2020-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=60, null=True, verbose_name='Должность'),
        ),
    ]
