# Generated by Django 3.1.1 on 2020-09-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200920_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
