# Generated by Django 3.1.1 on 2020-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200920_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото сотрудника'),
        ),
    ]
