# Generated by Django 3.1.1 on 2020-09-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
