# Generated by Django 3.1.1 on 2020-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201006_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='revenue',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход от покупки'),
        ),
    ]
