# Generated by Django 3.1.1 on 2020-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201006_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='purchases',
        ),
        migrations.AddField(
            model_name='customer',
            name='purchases',
            field=models.ManyToManyField(to='core.Purchase', verbose_name='Покупки пользователя'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
    ]
