# Generated by Django 3.1.1 on 2020-10-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201009_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='revenue',
        ),
    ]
