# Generated by Django 3.1.1 on 2020-10-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_purchase_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='Покупатель'),
        ),
    ]
