# Generated by Django 3.1.1 on 2020-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201009_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_num',
            field=models.IntegerField(null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_date',
            field=models.DateTimeField(verbose_name='Дата покупки'),
        ),
    ]
