# Generated by Django 3.1.2 on 2020-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201122_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpurchases',
            name='month',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Дата'),
        ),
    ]
